# Render Blueprint for automatic deployment
services:
  - type: web
    name: phishing-url-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: MODEL_URL
        value: https://github.com/ilyasiii/Phishing-URL-Prediction/releases/download/phishing/xgboost_model.pkl
      - key: FEATURE_URL
        value: https://github.com/ilyasiii/Phishing-URL-Prediction/releases/download/phishing/feature_extractor.pkl
      - key: PORT
        value: 8000
